steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build Docker image
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    id: Push Docker image
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA']
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
    id: Run Python Unittests
    args: ['tests.py']
    entrypoint: python
  - name: 'gcr.io/cloud-builders/gcloud'
    id: Deploy Flask app into test env
    entrypoint: bash
    secretEnv: ['POSTGRES_PWD', 'MAIL_PWD']
    args:
      - '-c'
      - |-
        gcloud run deploy notejam-test \ 
        --image "us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA" \
        --region us-central1 --platform managed --vpc-connector notejam-db-connector --port 5000 \
        --set-env-vars "FLASK_ENV=testing,MAIL_USER=notejam@freistrom.io,POSTGRES_URL=10.44.0.3:5432,POSTGRES_DB=notejam-test-db,POSTGRES_PWD=$$POSTGRES_PWD,MAIL_PW=$$MAIL_PWD"
availableSecrets:
  secretManager:
  - versionName: projects/419101208491/secrets/POSTGRES_PWD/versions/latest
    env: POSTGRES_PWD
  - versionName: projects/419101208491/secrets/MAIL_PWD/versions/latest
    env: MAIL_PWD
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
