steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'notejam:$BRANCH_NAME', '.' ]
  - name: 'notejam:$BRANCH_NAME'
    args: ['tests.py']
    env: 
      - 'FLASK_ENV=testing'
images:
  - 'notejam:$BRANCH_NAME'