steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA']
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
    args: ['tests.py']
    entrypoint: python
  - name: 'gcr.io/cloud-builders/gcloud'
    secretEnv: ['POSTGRES_PW', 'MAIL_PW']
    args:
      - 'run'
      - 'deploy'
      - 'notejam'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--vpc-connector' 
      - 'notejam-db-connector'
      - '--set-env-vars'
      - 'FLASK_ENV=testing,POSTGRES_PW=$$POSTGRES_PW,MAIL_USER=notejam@freistrom.io,POSTGRES_URL=10.44.0.3:5432,MAIL_PW=$$MAIL_PW'
      - '--port'
      - '5000'
availableSecrets:
  secretManager:
  - versionName: projects/PROJECT_ID/secrets/POSTGRES_PW/versions/1
    env: 'POSTGRES_PW'
  - versionName: projects/PROJECT_ID/secrets/MAIL_PW/versions/1
    env: 'MAIL_PW'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
