steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA']
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
    args: ['tests.py']
    entrypoint: python
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'notejam'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--vpc-connector' 
      - 'notejam-db-connector'
    env:
      - 'PORT=5000'
      - 'FLASK_ENV=testing'
      - 'MAIL_USER=notejam@freistrom.io'
      - 'MAIL_PW=mZ-Rj7A3Vj@-'
      - 'POSTGRES_URL=10.44.0.3:5432'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$COMMIT_SHA'
