steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$TAG_NAME', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$TAG_NAME']
  - name: 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$TAG_NAME'
    args: ['tests.py']
    env: 
      - 'FLASK_ENV=testing'
    entrypoint: python
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'notejam'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$TAG_NAME'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--vpc-connector' 
      - 'notejam-db-connector'
    env:
      - 'PORT=5000'
      - 'FLASK_ENV=production'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/notejam/notejam:$TAG_NAME'
